trigger:
  branches:
    include: ["master"]
  paths:
    include: ["Monolibs/lage/**"]

variables:
  workingDir: 'Monolibs/lage'
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
- stage: pre
  jobs:
  - job: preparation
    displayName: Preparation Job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | Monolibs/lage/package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: Cache npm

    - task: Npm@1
      inputs:
        command: 'ci'
        workingDir: '$(workingDir)'

    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: '$(workingDir)'
        customCommand: 'run lint:m'
      env:
        BACKFILL_CACHE_PROVIDER_OPTIONS: $(BACKFILL_CACHE_PROVIDER_OPTIONS)
        