trigger:
  branches:
    include:
    - master

stages:
- stage: build
  jobs:
  - job: build_job
    displayName: Build Angular
    pool:
      vmImage: windows-latest
    steps:
    - task: npm@1
      displayName: npm ci
      inputs:
        command: custom
        customCommand: 'ci'
    - task: npm@1
      displayName: npm start
      inputs:
        command: custom
        customCommand: 'start'
    - task: npm@1
      displayName: npm cypress
      inputs:
        command: custom
        customCommand: 'cypress:run'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'cypress/reports/junitreport.xml'
        mergeTestResults: true